name: ⭐ Generate Stared Repo List

on:
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: '0 1 * * *' # At 01:00.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Generate the list
      - name: Create star list
        id: stargazer
        uses: rverst/stargazer@v1.2.6
        with:
          github-user: ${{ github.actor }}
          github-token: ${{ secrets.GH_TOKEN }}
          list-file: "STARRED-REPOS.md"

      # Commit the changes
      - name: Commit files
        run: |
          git config --local user.email "vrusolik@gmail.com"
          git config --local user.name "arcestia"
          git add .
          git commit -m ":star: Updates Starred Repo List"

      # Push the changes
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_GH_TOKEN }}
          branch: ${{ github.ref }}
