name: GitHub-Profile-Summary-Cards

on:
  schedule: # Execute every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@v2.3.1
        env: # Setting an environment variable with the value of a GitHub token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          username: ${{ github.repository_owner }}
