name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: g1eny0ung/waka-box@v6.2.1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 01ed91aa2cb0025e9d60e81dab67c615
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          WAKATIME_BASE_URL: ${{ secrets.WAKATIME_BASE_URL }}
